### PR TITLE
Fix unclosable notification - refactor to Notifier

### LINKED ISSUE #147: Fix un-closeable "Complete your registration" notifications
Currently, the notifications from the `ApplicationMessageNotifier` are not closeable:

https://github.com/NIAEFEUP/nijobs-fe/blob/5b74eefc0cbb6e3ae8b046ed18cd377d622f3cd4/src/components/ApplicationMessages/index.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L9

The issue is that the handleClose handler is not being passed to the Notification ([here](https://github.com/NIAEFEUP/nijobs-fe/blob/5b74eefc0cbb6e3ae8b046ed18cd377d622f3cd4/src/components/ApplicationMessages/index.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L27))

There are many ways to fix this. But looking at our Notifications system implementation, we already had a "default" close handler defined in the [Notifier](https://github.com/NIAEFEUP/nijobs-fe/blob/5b74eefc0cbb6e3ae8b046ed18cd377d622f3cd4/src/components/Notifications/Notifier.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L32). The issue is that it is only used when we call the `addSnackbar` function with the default content, which is not the case in the `ApplicationMessageNotifier`.

---

To fix, we should refactor the Notifier to take notification content options as parameters, and have defaults for the non-required ones. This way, when we called addSanckbar, we could pass contentOptions to tweak the behavior, without having to pass the whole content object (The Notification would automatically be rendered by the Notifier, we would only pass contentOptions when calling `addSanckbar` if needed)

We would need to update other calls which use the content field as well when sending notifications. I only found this one: https://github.com/NIAEFEUP/nijobs-fe/blob/5b74eefc0cbb6e3ae8b046ed18cd377d622f3cd4/src/utils/UndoableActionsHandlerProvider.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L59

### PR DESCRIPTION
**Pull request by BrunoRosendo**
closes #147

### CODE REVIEW

File: src/utils/UndoableActionsHandlerProvider.js [hunk 1]
```diff
@@ -55,16 +54,13 @@ const BaseActionNotification = ({ action, removeAction, closeSnackbar, addSnackb
...
-                        actionHandler={handleCancel(key)}
-                        handleClose={handleClose(key)}
-                        onMouseEnter={handleMouseEnter}
-                        onMouseLeave={handleMouseLeave}
-                    />,
+            },
+            contentOptions: {
+                actionText: "Undo",
+                actionHandler: handleCancel(action.id),
+                handleClose: handleClose(action.id),
```
Comment (BrunoRosendo) [inline src/utils/UndoableActionsHandlerProvider.js:61]: Is passing `action.id` fine? This is not a raw prop anymore so it doesn't recognize `key`

Comment (imnotteixeira) [reply src/utils/UndoableActionsHandlerProvider.js:61]: I'm not following, could you elaborate?

File: src/components/Notifications/Notifier.js [hunk 2]
```diff
@@ -19,7 +19,7 @@ const Notifier = ({ notifications, removeSnackbar }) => {
     };
 
     React.useEffect(() => {
-        notifications.forEach(({ key, message, options = {}, dismissed = false }) => {
+        notifications.forEach(({ key, message, options = {}, contentOptions = {}, dismissed = false }) => {
```
Comment (imnotteixeira) [inline src/components/Notifications/Notifier.js:22]: Add a comment to the addSnackbar function, mentioning the possible parameters, and especially the fact that `options` has precedence over `contentOptions`. If both are present and `options.content` is set, `contentOptions` will not be used

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

File: src/utils/UndoableActionsHandlerProvider.js (hunk 1 above)
Comment (BrunoRosendo) [reply src/utils/UndoableActionsHandlerProvider.js:61]: We already spoke about this in the meeting but I had to specify `action.id` since this is not a raw prop anymore

**Review by DoStini — APPROVED** [review]

**Review by imnotteixeira — APPROVED** [review]
