### PR TITLE
Fix Offer title redirect

### LINKED ISSUE #164: Wrong redirect
Replace "href" with "to"
https://github.com/NIAEFEUP/nijobs-fe/blob/d6d0d2fd0f08c6600857259112cc6dc11ea27067/src/components/HomePage/SearchResultsArea/Offer/OfferDetails.js#L74

### PR DESCRIPTION
**Pull request by DoStini**
closes #164

### CODE REVIEW

File: src/components/HomePage/SearchResultsArea/Offer/OfferDetails.js [hunk 1]
```diff
@@ -71,7 +72,7 @@ const OfferDetails = ({
                                 isPage ?
                                     offer.title
                                     :
-                                    <Link href={`/offer/${offer._id}`} className={classes.offerTitleLink}>
+                                    <Link to={`/offer/${offer._id}`} component={RouterLink} className={classes.offerTitleLink}>
```
Comment (imnotteixeira) [inline src/components/HomePage/SearchResultsArea/Offer/OfferDetails.js:75]: Why did you need the RouterLink?

**Review by imnotteixeira — APPROVED** [review]

File: src/components/HomePage/SearchResultsArea/Offer/OfferDetails.js (hunk 1 above)
Comment (DoStini) [reply src/components/HomePage/SearchResultsArea/Offer/OfferDetails.js:75]: I replaced `href` with `to` and when I clicked in it, nothing happened. Also hovering was not showing the correct link. I saw this `component router link` somewhere in the code and it worked, not really sure why

**Review by TiagooGomess — APPROVED** [review]
