### PR TITLE
Fix/nijobs logo mobile landscape

### LINKED ISSUE #161: Fix NIJobs logo when  in landscape mode
When in landscape mode, NIjobs logo should be about 20vh

### PR DESCRIPTION
**Pull request by pedronunes19**
Closes #161 . Previously, the NIJobs logo occupied 80% of available width in any mobile view. This should change that, leaving the logo in mobile landscape view looking closer to the desktop view. The solution isn't as great as I wanted, as I couldn't figure out a way to variably define the percentage of the page width the logo should take. Feedback is much appreciated.

image

image

### CODE REVIEW

**Comment by pedronunes19** [comment]
Now vh is used in order for the logo's height to max at 20vh

image

File: src/components/HomePage/mainViewStyles.js [hunk 1]
```diff
@@ -9,8 +9,12 @@ export default makeStyles((theme) => ({
     mainLogo: ({ isMobile }) => ({
         textAlign: "center",
         paddingBottom: "3em",
+        display: "flex",
+        alignItems: "center",
+        justifyContent: "center",
         "& img": {
             width: isMobile ? "80%" : "50%",
+            maxHeight: isMobile ? "max(20vh, 6em)" : "unset",
```
Comment (Naapperas) [inline src/components/HomePage/mainViewStyles.js:17]: How did you arrive at these values ?

**Review by Naapperas — APPROVED** [review]
I think this works but my sense of style is not the best so I'll ask some other people to review this.

File: src/components/HomePage/mainViewStyles.js (hunk 1 above)
Comment (pedronunes19) [reply src/components/HomePage/mainViewStyles.js:17]: 20vh was the suggestion given in the linked issue. 6em is an arbitrary value I picked after experimenting a bit, to keep image from reducing its size too much in very small displays. I'll take suggestions.

**Review by BrunoRosendo — APPROVED** [review]
This looks good to me, it's working as expected. @DoStini Do you have some opinion regarding the fix itself?

**Comment by Naapperas** [comment]
This will be merged in the next release so it's merge will be put on hold.

**Comment by Naapperas** [comment]
@pedronunes19 rebase so this can be merged

**Comment by pedronunes19** [comment]
Rebase done @Naapperas
