### PR TITLE
Lost state fix

### LINKED ISSUE #115: The state is lost when switching from desktop to mobile view and vice-versa
The session was being lost in some pages, so we needed to set revalidateOnMount to true [here](https://github.com/NIAEFEUP/nijobs-fe/blob/develop/src/components/Navbar/index.js#L30), in #105.

Because of this change, the state is being lost in some pages when switching from desktop to mobile view or vice-versa, namely in the finish registration page.

What is happening is:
1. Unmount of PageLayout
2. Show loading
3. Mount PageLayout again

A possible solution for this is to do not let PageLayout re-render, even if the session changes. In theory, we can try to move the Controller Pattern to the Route level, but we need to see if that would work.

### PR DESCRIPTION
**Pull request by TiagooGomess**
Closes #115

### CODE REVIEW

File: src/components/Layout/PageLayout.js [hunk 1]
```diff
@@ -1,11 +1,12 @@
-import React, { useEffect } from "react";
+import React, { useContext, useEffect } from "react";
 import PropTypes from "prop-types";
 import { useMobile } from "../../utils/media-queries";
-import useComponentController from "../../hooks/useComponentController";
 import DesktopLayout from "./DesktopLayout";
 import MobileLayout from "./MobileLayout";
 import BaseLayout from "./BaseLayout";
 
+const DefaultContext = React.createContext();
```
Comment (imnotteixeira) [inline src/components/Layout/PageLayout.js:8]: import the default context from the useComponentController file (https://github.com/NIAEFEUP/nijobs-fe/blob/develop/src/hooks/useComponentController.js) It's the same for now, but if we ever need to change it, it's better to use the same

File: src/components/Layout/PageLayout.js [hunk 2]
```diff
@@ -31,32 +32,31 @@ const PageLayout = ({
...
 }) => {
 
-    const { ContextProvider, contextProviderProps, ...contextValues } = useComponentController(controller, controllerProps, context);
-
     useEffect(() => {
         document.title = pageTitle ? `${pageTitle} - NIJobs` : "NIJobs";
     }, [pageTitle]);
 
+    const usedContext = context ? context : DefaultContext;
+    const contextValues = useContext(usedContext || DefaultContext);
```
Comment (imnotteixeira) [inline src/components/Layout/PageLayout.js:46]:
```suggestion
    const contextValues = useContext(context || DefaultContext);
```

File: src/utils/index.js [hunk 3]
```diff
@@ -127,35 +128,72 @@ const mapDispatchToProps = (dispatch) => ({
 });
 const RedirectInfoProvider = connect(mapStateToProps, mapDispatchToProps)(BaseRedirectInfoProvider);
 
-export const Route = ({ children, ...props }) => (
+/* istanbul ignore next */
```
Comment (imnotteixeira) [inline src/utils/index.js:131]: why is this needed?

File: src/utils/index.js [hunk 4]
```diff
@@ -191,10 +230,57 @@ export const ProtectedRoute = ({
...
+    controllerProps,
+    // eslint-disable-next-line react/prop-types
+    context,
+    ...routeProps
+}) => (
+    <Route
+        {...routeProps}
+    >
+        <ProtectedRouteController
+            isProtected
```
Comment (imnotteixeira) [inline src/utils/index.js:270]:
```suggestion
```

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

File: src/utils/index.spec.js [hunk 5]
```diff
@@ -47,24 +52,214 @@ describe("utils", () => {
...
                 <Wrap on={false} Wrapper={WrapperComponent}>
                     <p>Hello</p>
                 </Wrap>
             );
 
-            expect(wrapper.queryByTestId("test")).not.toBeInTheDocument();
-            expect(wrapper.getByText("Hello")).toBeInTheDocument();
+            expect(screen.queryByTestId("test")).not.toBeInTheDocument();
+            expect(screen.getByText("Hello")).toBeInTheDocument();
+        });
```
Comment (imnotteixeira) [inline src/utils/index.spec.js:73]: nice 👍

**Review by imnotteixeira — APPROVED** [review]
Nice tests, good job 🚀
