### PR TITLE
Fix no padding in offer preview in search page

### LINKED ISSUE #162: Add padding at the bottom of search offers page
Should add padding to the content of an offer in search offers page

image

### PR DESCRIPTION
**Pull request by DoStini**
closes #162

### CODE REVIEW

File: src/components/HomePage/SearchResultsArea/Offer/OfferWidget.js [hunk 1]
```diff
@@ -81,7 +81,7 @@ const OfferWidget = ({
                         </Typography>
                     </div>
                     :
-                    <div>
+                    <div className={!isPage ? classes.searchOfferPadding : ""}>
```
Comment (TiagooGomess) [inline src/components/HomePage/SearchResultsArea/Offer/OfferWidget.js:84]:
```suggestion
                    <div className={!isPage && classes.searchOfferPadding}>
```

**Review by TiagooGomess — CHANGES_REQUESTED** [review]

File: src/components/HomePage/SearchResultsArea/SearchResultsWidget/searchResultsWidgetStyles.js [hunk 2]
```diff
@@ -96,6 +96,9 @@ export default makeStyles((theme) => ({
     offerTitleLink: {
         color: "inherit",
     },
+    searchOfferPadding: {
```
Comment (TiagooGomess) [inline src/components/HomePage/SearchResultsArea/SearchResultsWidget/searchResultsWidgetStyles.js:99]:
```suggestion
    offerContainer: {
```

**Review by TiagooGomess — CHANGES_REQUESTED** [review]

**Review by TiagooGomess — APPROVED** [review]
Rebase and it's ready
