### PR TITLE
Fixed 'Show Me' not closing notification

### LINKED ISSUE #207: Clicking "Show me button" in notification not closing

### PR DESCRIPTION
**Pull request by BrunoRosendo**
closes #207

### CODE REVIEW

**Review by DoStini — CHANGES_REQUESTED** [review]

File: src/components/ApplicationMessages/index.js [hunk 1]
```diff
@@ -13,23 +14,29 @@ const ApplicationMessageNotifier = ({ addSnackbar }) => {
     const history = useHistory();
 
     const { data, isLoggedIn, revalidate, isValidating } = useSession();
+    const { closeSnackbar } = useSnackbar();
```
[the remark this answers is not in the document]
Comment (BrunoRosendo) [reply src/components/ApplicationMessages/index.js:17]: Should it work the same way? I tried that one first but it wasn't working

[the remark this answers is not in the document]
Comment (imnotteixeira) [reply src/components/ApplicationMessages/index.js]: I don't remember having a snackbar hook, so not sure if you should be using that, I'll check

File: src/components/ApplicationMessages/index.js [hunk 2]
```diff
@@ -18,18 +18,23 @@ const ApplicationMessageNotifier = ({ addSnackbar }) => {
         if (!hasRevalidated || isValidating) return;
         if (isLoggedIn && !data.isAdmin && !data.company?.hasFinishedRegistration && !hasShownCompleteRegistrationMessage) {
             setHasShownCompleteRegistrationMessage(true);
+
+            // Overrides key from addSnackbar()
+            const key = Date.now() + Math.random();
```
Comment (imnotteixeira) [inline src/components/ApplicationMessages/index.js:23]: Keys are internal to the notification system. Consumers should not know about them. I think this is a common enough scenario to make it available generaly:

Add an option to the notification, specifying if the action click should close the notification or not (I think the default should be true, but check other cases to see if it applies)

Then, somewhere [here](https://github.com/NIAEFEUP/nijobs-fe/blob/463cc3dc2738807af803c4c017b8b5da6915be06/src/components/Notifications/Notifier.js#L31), we wrap the actionHandler in a function that based on the flag calls the `closeSnackbar` (not the `handleClose`! Those are different things and the latter should only be called when the user actually closes notifications)

File: src/components/ApplicationMessages/index.js [hunk 3]
```diff
@@ -18,18 +18,23 @@ const ApplicationMessageNotifier = ({ addSnackbar }) => {
...
                     actionHandler: () => {
                         history.push("/company/registration/finish");
+                        closeSnackbar(key);
                     },
                 },
             });
         }
         if (hasShownCompleteRegistrationMessage && !isLoggedIn) setHasShownCompleteRegistrationMessage(false);
-    }, [addSnackbar, data, hasRevalidated, hasShownCompleteRegistrationMessage, history, isLoggedIn, isValidating]);
+    }, [addSnackbar, closeSnackbar, data, hasRevalidated, hasShownCompleteRegistrationMessage, history, isLoggedIn, isValidating]);
```
Comment (imnotteixeira) [inline src/components/ApplicationMessages/index.js:37]:
```suggestion
    }, [addSnackbar, data, hasRevalidated, hasShownCompleteRegistrationMessage, history, isLoggedIn, isValidating]);
```

File: src/components/ApplicationMessages/index.js [hunk 4]
```diff
@@ -1,11 +1,11 @@
 import { useEffect, useState } from "react";
 import PropTypes from "prop-types";
-import { addSnackbar } from "../../actions/notificationActions";
+import { addSnackbar, closeSnackbar } from "../../actions/notificationActions";
 import useSession from "../../hooks/useSession";
 import { connect } from "react-redux";
 import { useHistory } from "react-router";
 
-const ApplicationMessageNotifier = ({ addSnackbar }) => {
+const ApplicationMessageNotifier = ({ addSnackbar, closeSnackbar }) => {
```
Comment (imnotteixeira) [inline src/components/ApplicationMessages/index.js:8]:
```suggestion
const ApplicationMessageNotifier = ({ addSnackbar}) => {
```

File: src/components/ApplicationMessages/index.js [hunk 5]
```diff
@@ -1,11 +1,11 @@
 import { useEffect, useState } from "react";
 import PropTypes from "prop-types";
-import { addSnackbar } from "../../actions/notificationActions";
+import { addSnackbar, closeSnackbar } from "../../actions/notificationActions";
```
Comment (imnotteixeira) [inline src/components/ApplicationMessages/index.js:3]:
```suggestion
import { addSnackbar } from "../../actions/notificationActions";
```

File: src/components/ApplicationMessages/index.js [hunk 6]
```diff
@@ -18,18 +18,23 @@ const ApplicationMessageNotifier = ({ addSnackbar }) => {
         if (!hasRevalidated || isValidating) return;
         if (isLoggedIn && !data.isAdmin && !data.company?.hasFinishedRegistration && !hasShownCompleteRegistrationMessage) {
             setHasShownCompleteRegistrationMessage(true);
+
+            // Overrides key from addSnackbar()
+            const key = Date.now() + Math.random();
             addSnackbar({
                 message: "In order to fully use NIJobs, you still need to finish your registration.",
+                key,
```
Comment (imnotteixeira) [inline src/components/ApplicationMessages/index.js:26]:
```suggestion
```

File: src/components/ApplicationMessages/index.js [hunk 7]
```diff
@@ -18,18 +18,23 @@ const ApplicationMessageNotifier = ({ addSnackbar }) => {
...
                 contentOptions: {
                     actionText: "Show me",
                     actionHandler: () => {
                         history.push("/company/registration/finish");
+                        closeSnackbar(key);
```
Comment (imnotteixeira) [inline src/components/ApplicationMessages/index.js:31]:
```suggestion
```

File: src/components/ApplicationMessages/index.js [hunk 8]
```diff
@@ -49,6 +54,7 @@ ApplicationMessageNotifier.propTypes = {
 const mapStateToProps = () => ({});
 const mapDispatchToProps = (dispatch) => ({
     addSnackbar: (notification) => dispatch(addSnackbar(notification)),
+    closeSnackbar: (key) => dispatch(closeSnackbar(key)),
```
Comment (imnotteixeira) [inline src/components/ApplicationMessages/index.js:57]:
```suggestion
```

File: src/pages/HomePage.spec.js [hunk 9]
```diff
@@ -29,7 +29,9 @@ describe("HomePage", () => {
 
             renderWithStoreAndTheme(
                 <Router>
-                    <HomePage />
+                    <SnackbarProvider maxSnack={3}>
```
Comment (imnotteixeira) [inline src/pages/HomePage.spec.js:32]: Confirm if you still need this provider. Probably not.

File: src/pages/HomePage.spec.js [hunk 10]
```diff
@@ -52,7 +54,9 @@ describe("HomePage", () => {
...
```
Comment (imnotteixeira) [inline src/pages/HomePage.spec.js:57]: Confirm if you still need this provider. Probably not.

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

**Review by DoStini — APPROVED** [review]

File: src/components/Notifications/Notifier.js [hunk 11]
```diff
@@ -29,11 +31,17 @@ const Notifier = ({ notifications, removeSnackbar }) => {
             // do nothing if snackbar is already displayed
             if (displayed.current.includes(key)) return;
 
+            const closableActionHandler = contentOptions.actionHandler ? () => {
+                contentOptions.actionHandler();
+                closeSnackbar(key);
+            } : null;
+
```
Comment (imnotteixeira) [inline src/components/Notifications/Notifier.js:38]:
```suggestion
            const actionHandler = contentOptions.actionHandler ? () => {
                contentOptions.actionHandler();
                if(closeOnAction) closeSnackbar(key);
            } : (() => {});

```

File: src/components/Notifications/Notifier.js [hunk 12]
```diff
@@ -29,11 +31,17 @@ const Notifier = ({ notifications, removeSnackbar }) => {
...
             const configuredContent = (key, message) =>
                 <Notification
                     {...contentOptions}
                     message={contentOptions.message || message}
                     handleClose={contentOptions.handleClose || (() => closeSnackbar(key))}
+                    actionHandler={closeOnAction ? closableActionHandler : contentOptions.actionHandler}
```
Comment (imnotteixeira) [inline src/components/Notifications/Notifier.js:44]:
```suggestion
                    actionHandler={actionHandler}
```

File: src/utils/UndoableActionsHandlerProvider.js [hunk 13]
```diff
@@ -57,7 +56,7 @@ const BaseActionNotification = ({ action, removeAction, closeSnackbar, addSnackb
             },
             contentOptions: {
                 actionText: "Undo",
-                actionHandler: handleCancel(action.id),
+                actionHandler: handleCancel,
```
Comment (imnotteixeira) [inline src/utils/UndoableActionsHandlerProvider.js:59]: The comment does not apply to this line but I cannot select the correct one...

This useEffect has dependencies that are no longer used, erase them all, and let eslint fix it for you automatically, so that you only depend on what you need

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

**Review by imnotteixeira — APPROVED** [review]
