### PR TITLE
Fixed finish registration badge showing for admin

### LINKED ISSUE #112: Finish registration badge is showing for admin
This account is the default admin, it shouldn't have to complete any registration.

image

### PR DESCRIPTION
**Pull request by TiagooGomess**
Closes #112

### CODE REVIEW

File: src/components/Navbar/UserMenu.js [hunk 1]
```diff
@@ -86,6 +86,37 @@ AdminMenuOptions.propTypes = {
...
+                    color="primary"
+                    anchorOrigin={{ horizontal: "left", vertical: "top" }}
+                >
+                    <Box pl={2}>
+                        Finish Registration
+                    </Box>
+                </Badge>
+            </MenuItem>
+        );
+    }
```
Comment (imnotteixeira) [inline src/components/Navbar/UserMenu.js:117]: This is not very future proof (if we want to add a new option that shows regardless of that condition you would have to add it to both branches (if/else)

You can do it like this instead:
```
return (
<>
{sessionData.company.hasFinishedRegistration ? 
    <MyOffers stuff>
    : <FinishRegistration stuff>
}
// stuff that goes here shows every time
</>
)
```

Comment (imnotteixeira) [reply src/components/Navbar/UserMenu.js:117]: Also use `sessionData?.company?.hasFinishedRegistration` since if the logged in user is an admin, it would crash

**Review by imnotteixeira — CHANGES_REQUESTED** [review]

**Review by imnotteixeira — APPROVED** [review]
